name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: Swatinem/rust-cache@v2

    - name: Build
      run: cargo build --verbose

    - name: Run tests
      run: cargo test --verbose

    - name: Run clippy
      run: cargo clippy

    - name: Run fmt
      run: cargo fmt --check

    - name: Run barebones tests
      run: cargo test --no-default-features --lib

    - name: Run complete tests
      run: cargo test --all-features

    - name: Run web tests
      run: cargo test --features "web"

    # - name: Check if the README is up to date.
    #   run: |
    #     cargo install cargo-rdme
    #     cargo rdme --check
